# Generated by Django 4.2.5 on 2023-09-06 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_appunto', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf_appunto', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('voto_medio', models.IntegerField(blank=True, null=True)),
                ('Num_scaricamento', models.IntegerField()),
                ('data_caricamento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codMat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Studente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('dataNascita', models.DateField()),
                ('password', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cancella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cancellazione', models.DateTimeField()),
                ('appunto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appunti.appunto')),
                ('studente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appunti.studente')),
            ],
        ),
        migrations.AddField(
            model_name='appunto',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appunti.materia'),
        ),
        migrations.AddField(
            model_name='appunto',
            name='studente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appunti.studente'),
        ),
        migrations.CreateModel(
            name='Scarica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_scaricamento', models.DateTimeField()),
                ('voto_assegnato', models.IntegerField(blank=True, null=True)),
                ('appunto_scaricato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appunti.appunto')),
                ('studente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appunti.studente')),
            ],
            options={
                'unique_together': {('studente', 'appunto_scaricato', 'data_scaricamento')},
            },
        ),
        migrations.CreateModel(
            name='Recenzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recenzione', models.DateTimeField()),
                ('testo_recenzione', models.CharField(max_length=200)),
                ('appunto_recenzionato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appunti.appunto')),
                ('studente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appunti.studente')),
            ],
            options={
                'unique_together': {('studente', 'appunto_recenzionato', 'data_recenzione')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='appunto',
            unique_together={('nome_appunto', 'pdf_appunto')},
        ),
    ]
