# Generated by Django 4.2.5 on 2023-09-13 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appunti', '0002_studente_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studente',
            name='Username',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studente',
            name='dataNascita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studente',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studente',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
