# Generated by Django 4.2.5 on 2023-09-19 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appunti', '0003_alter_studente_username_alter_studente_datanascita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appunto',
            name='studente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appunti.studente'),
        ),
    ]
